#!/bin/bash

if [ "$(whoami)" == "root" ]; then
    echo
    echo "SetUpSystem als Root aufgerufen: ABBRUCH!"
    echo
    exit 1
fi

#Git einrichten:
git config --global include.path "~/dotfiles/_gitconfig"
git config --global user.name "Daniel"
git config --global user.email "none"

#Github persönliche Files runterladen:
git clone https://github.com/Wagawonga/Linux-Vimfiles.git ~/dotfiles
git clone https://github.com/Wagawonga/bin.git ~/bin

#vim einreichten:
echo 'source ~/dotfiles/_vimrc.vim' > ~/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +'colorsheme default' +PluginInstall +qall

#zu .bashrc hinzufügen
RCLINE='source ~/dotfiles/_bashrc'
if ! grep -q "$RCLINE" ~/.bashrc ;then
    echo $RCLINE >> ~/.bashrc 
fi
unset RCLINE

#Tmux config fuer 256 Farben kopieren
echo 'source  ~/dotfiles/.tmux.conf' > ~/.tmux.conf
