#!/bin/bash

#Dies soll ein Tippprogramm werden, dass als ersten
#Parameter ein Textfile erhaelt und diesen Text vom Benutzer
#Tippen lässt. Bei einem
#Fehler muss der gesamte Text von vorne eingetippt werden.
#Features TODO:
#   1. Zeitmessung
#   2. Log
#   3. Anschläge pro Minute anzeigen.
#   4. Prozentanzeige & Zeitanzeige.

#Text einlesen:
test=''
if [ $1 ]; then
    text="$(cat $1)";
else
    echo KEINE TEXTDATEIN ANGEGEBEN
    exit 1;
fi

echo
echo '---------------------'
echo 'Zeilen:  ' $(wc -l < $1)
echo 'Wörter:  ' $(wc -w < $1)
echo 'Zeichen: ' $(wc -m < $1)
echo '---------------------'
echo
echo '- Los gehts! -'
echo
echo

#Tasten lesen:
ifsOri=$IFS
count=0
while true; do
    # Zu schreiben Text anzeigen:
    echo -ne "\033[1A\033[0K"
    IFS=''
    echo ${text:count:50} | cut -f1 -d$'\n' 
    
    #Buchstabe einlesen:
    read -rsd '' -n1 input;
    #echo -n $count

    #Vergleich:
    if [ $input != ${text:count:1}  ]; then
        echo Fehler gemacht! ENDE!
        exit 1
    fi

    IFS=$ifsOri
    
    count=$(( $count + 1 ))
    
    #Textende
    if [ ${#text} -le $count ];then
        echo GEWONNEN!!!
        exit 0
    fi
done
