#!/bin/bash
if [ "$(whoami)" == "root" ]; then
    echo
    echo "SetUpSystem als Root aufgerufen: ABBRUCH!"
    echo
    exit 1
fi


#Git einrichten:
git config --global include.path "~/dotfiles/_gitconfig"
git config --global user.name "Daniel"
git config --global user.email "none"

#Um das __git_ps1 Problem zu lösen:
curl -L https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh > ~/.bash_git

#Github persönliche Files runterladen:
git clone https://github.com/Wagawonga/Linux-Vimfiles.git ~/dotfiles
git clone https://github.com/Wagawonga/bin.git ~/bin

addLineToRC 'source ~/dotfiles/_vimrc.vim' ~/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +'colorsheme defaul://raw.github.com/git/git/master/contrib/cot' +PluginInstall +qall

addLineToRC 'source ~/dotfiles/_bashrc' ~/.bashrc
addLineToRC 'source ~/dotfiles/_tmux.conf' ~/.tmux.conf
./setUpMutt

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh-syntax-highlighting
addLineToRC 'source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' ~/.zshrc

pip3 install --user goobook #Goobook für Mutt intallieren muss aber noch authentifiziert werden!
~/.local/bin/goobook authenticate
pip3 install --user thefuck
pip install --user maybe
